name: Build trendszine Extension

on:
  workflow_dispatch: # 允许在网页上手动点击触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build trendszine APK
        # 注意：这里的 :src:en:misskon 假设 misskon 在 en(英文) 目录下。
        # 如果编译报错找不到模块，请看下方【重要提示】修改这里。
        run: ./gradlew :src:all:trendszine:assembleRelease --no-daemon

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trendszine-release-apk
          # 使用通配符自动寻找生成的 apk 文件
          path: src/*/trendszine/build/outputs/apk/release/*.apk
          if-no-files-found: error